[tool.poetry]
name = "nx_core"
version = "0.1.0"
description = ""
authors = ["xyder <xyder@dsider.org>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
maturin = "^0.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
