[package]
name = "security"
version = "0.1.0"
authors = ["xyder <xyder@dsider.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "^0.16"
base64 = "0.13.0"
